services:
  moviecat-backend:
    container_name: moviecat-backend
    build: ./moviecat-backend
    env_file:
      - ./.env
    networks:
      - newtone
    volumes:
      - dkim_data:/etc/opendkim/keys/:ro
    depends_on:
      - moviecat-redis
      - moviecat-postgresql

  moviecat-web:
    container_name: moviecat-web
    build: ./moviecat-web
    env_file:
      - ./.env
    networks:
      - newtone
    depends_on:
      - moviecat-backend

  moviecat-postgresql:
    image: postgres
    container_name: moviecat-postgresql
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      - moviecat_postgres_data:/var/lib/postgresql/data
    networks:
      - newtone

  moviecat-adminer:
    image: adminer
    container_name: moviecat-adminer
    restart: always
    networks:
      - newtone
  moviecat-redis:
    container_name: moviecat-redis
    image: redis
    restart: always
    networks:
      - newtone
    volumes:
      - moviecat_redis_data:/data

networks:
  newtone:
    external: true

volumes:
  moviecat_postgres_data:
    external: true
  moviecat_redis_data:
    external: true
  dkim_data:
    external: true
